### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by bckp** [athombv/com.plugwise.adam#10]
Hi, i have missing some functions for my Anna, like if boiler is or is not active (ideally with insights), lux, motion will be nice, and what is most important, feedback from plugwise about mode, i can set mode, but homey do not remember it, or cant read it, so now i need to do kind ugly and big flows, temperatures in App and in Plugwise itself etc... better to have temperatures on one place (plugwise) and with Homey just send changes to mode, or read change done by user...

**Comment by WeeJeWel** [comment]
Anna's mode does now sync in v2.5.0.

**Comment by bckp** [comment]
<3

**Comment by bckp** [comment]
Can you add : when state is changed? For case, when user change it from Anna
