### ISSUE TITLE
Anna doesnt work anymore after the 4.0.27. firmware update that rolled out

### ISSUE THREAD

**Issue by mruiter** [athombv/com.plugwise.adam#13]
Anna gives a port 80 http error when you try to connect / change anything on a connected devices.

A remove and a try to pair again gives no available devices anymore. Anna cant be found 

This happend after Plugwise pushed the 4.0.27 firmware for the Anna devices.

Since its a vendor verified app i guess they are already on it ?

**Comment by WeeJeWel** [comment]
Fixed
