### ISSUE TITLE
Crippled version as replacement of good app. 

### ISSUE THREAD

**Issue by JMeinen69** [athombv/com.plugwise.adam#5]
Hi there, first of al great work for making apps for Anna. 
Why is this version released and the old one removed before it has al the functionality the old app has? (reading sensors in Anna and use them in flows, now lots of my flows wont work any more. Not able to use presets instead of setting temp.)
Now its a crippled version of the great app that's removed. 

Wil all those functions come back soon? Is it possible to put the old version back to the app store till it does?

**Comment by WeeJeWel** [comment]
See #7
