### ISSUE TITLE
Missing functionality in new app

### ISSUE THREAD

**Issue by jhlos** [athombv/com.plugwise.adam#7]
Hi,

The old Anna app is no longer supported, but the new one has less functionality. I understand that you want te merge some apps supporting devices from the same brand, but I don't get it that you do this when this means that the support of one of the devices en much lower.

I suggest that you lose the support of the Anna in this app and keep supporting the old Anna app with a higher support level of the device.

**Comment by WeeJeWel** [comment]
Hi @jhlos, we will not reverse this decision.

Which functionalities are you missing?

**Comment by jhlos** [comment]
I understand that you prefer one app in stead of two.

In the old app there was a page (long press and then the second page I think) where I could see the status of my heater (pressure and status code)

All these settings could also be found in the insights page
